package BackEnd;

public enum TipoLancamento {
    // Receitas
    SALARIO,
    HORAS_EXTRAS,
    COMISSOES,
    INVESTIMENTOS,
    FREELANCER,
    VENDA_DE_BENS,
    APOSENTADORIA,
    REEMBOLSOS,
    PREMIOS_E_SORTEIOS,
    VENDA,
    BOLSA_DE_ESTUDO,
    AUXILIO_DO_GOVERNO,
    CASHBACKS,
    INDENIZACAO,

    // Despesas
    ALUGUEL,
    CONTA_DE_LUZ,
    CONTA_DE_AGUA,
    INTERNET_E_TELEFONE,
    ALIMENTACAO,
    ENTRETENIMENTO_LAZER,
    SAUDE,
    CARTAO_DE_CREDITO,
    MULTAS,
    SEGURO_DO_VEICULO,
    COMBUSTIVEL,
    ASSINATURAS_DE_STREAMING,
    EDUCACAO,
    ROUPAS_E_ACESSORIOS,
    IMPOSTOS,

    // Outros
    OUTROS
}
